// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogging.Models;

namespace blogging.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201115060546_database")]
    partial class database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("blogging.Models.story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 407, DateTimeKind.Local).AddTicks(6702),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 2,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 408, DateTimeKind.Local).AddTicks(5656),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 3,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 408, DateTimeKind.Local).AddTicks(5680),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 4,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 408, DateTimeKind.Local).AddTicks(5683),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 5,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 408, DateTimeKind.Local).AddTicks(5685),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 6,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 11, 35, 46, 408, DateTimeKind.Local).AddTicks(5686),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
