// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogging.Models;

namespace blogging.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201115063310_login")]
    partial class login
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("blogging.Models.Users", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photopath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("blogging.Models.story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 185, DateTimeKind.Local).AddTicks(7373),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 2,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 187, DateTimeKind.Local).AddTicks(2108),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 3,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 187, DateTimeKind.Local).AddTicks(2137),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 4,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 187, DateTimeKind.Local).AddTicks(2140),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 5,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 187, DateTimeKind.Local).AddTicks(2142),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 6,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 15, 12, 3, 10, 187, DateTimeKind.Local).AddTicks(2143),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
