// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using blogging.Models;

namespace blogging.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("blogging.Models.Users", b =>
                {
                    b.Property<string>("email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photopath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("blogging.Models.story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 94, DateTimeKind.Local).AddTicks(1415),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 2,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 95, DateTimeKind.Local).AddTicks(938),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 3,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 95, DateTimeKind.Local).AddTicks(959),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 4,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 95, DateTimeKind.Local).AddTicks(961),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 5,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 95, DateTimeKind.Local).AddTicks(963),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        },
                        new
                        {
                            Id = 6,
                            body = "cdsgrsdg",
                            createdat = new DateTime(2020, 11, 18, 13, 31, 31, 95, DateTimeKind.Local).AddTicks(964),
                            status = 0,
                            title = "blogging",
                            userId = "vfg@gmial.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
